# Site settings
title: Clyde's Product Reviews
description: I review the best products, tools, and services to help you make the right decision.
author: Clyde Barker

# Build settings
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

# Personalization
navbar-links:
  Home: "/"
  About: "about"
  Reviews: "reviews"
  Privacy Policy: "privacy-policy"
  Contact: "contact"

# --- General options --- #
url: "https://parasiticleech.github.io"
baseurl: ""

# Title link configuration
title-img: false  # Set to false if you want to use text title
# If you want a title image instead, specify the path here
# title-img: /path/to/title-image.png

# Whether the title should link to the home page
# Set to true to enable the link
title-link: true

# Default YAML values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

# Pagination
paginate: 10
paginate_path: "/reviews/page:num/"

# Additional settings from your original config
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Post settings
post_excerpts: true
excerpt_length: 50
read_more_link_text: "Read more..."

# Default settings for blog posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
      readtime: true
